name: Build and Deploy to JFrog

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

env:
  PYTHON_VERSION: '3.11'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout código
      uses: actions/checkout@v4
      
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}
        
    - name: Instalar dependências
      run: |
        python -m pip install --upgrade pip
        pip install build twine hatchling
        
    - name: Build do pacote
      run: |
        python -m build
        ls -la dist/
        
    - name: Deploy para JFrog
      env:
        JFROG_URL: ${{ secrets.JFROG_URL }}
        JFROG_USER: ${{ secrets.JFROG_USER }}
        JFROG_TOKEN: ${{ secrets.JFROG_TOKEN }}
      run: |
        python -m twine upload \
          --repository-url $JFROG_URL \
          --username $JFROG_USER \
          --password $JFROG_TOKEN \
          dist/*
          
    - name: Criar Release no GitHub
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: dist/*
        body: |
          ## MCP Busca Município Validador ${{ github.ref_name }}
          
          ### Instalação
          
          Via uvx:
          ```bash
          uvx install mcp-busca-municipio-validador --index-url ${{ secrets.JFROG_URL }}
          ```
          
          Via pip:
          ```bash
          pip install mcp-busca-municipio-validador --index-url ${{ secrets.JFROG_URL }}
          ``` 